### PR TITLE
Add xcbeautify to the compatible packages

### PR DESCRIPTION
**Pull request by thii**
Hi! It would be nice to have xcbeautify in the list of compatible packages.

### CODE REVIEW

**Comment by imaizume** [comment]
@yonaskolb Do you think of providing alternative way to aggregate all of mint compatible libraries?
If making pull request by authors is a only way to do that, it would be burden for you to updating the information latest some day... 😓

**Comment by toshi0383** [comment]
Almost all Swift Packages are mint compatible anyways?🤔 (so I don't think we officially need one.)

**Comment by yonaskolb** [comment]
Yeah, I was thinking of actually taking that section out. Another resource could be used to find all Swift packages that vend executable products. My hope is that something like https://swiftpm.co will add a search filter for executables. It currently display whether a package has an executable (https://swiftpm.co/?query=xcodegen) but there's no way to see ALL the packages that have executables

**Comment by yonaskolb** [comment]
I've opened an issue here to track being able to filter packages by executable https://github.com/daveverwer/SwiftPMLibrary/issues/198

**Pull request merged**
