### PR TITLE
Add which command for printing full path to binary

### PR DESCRIPTION
**Pull request by LinusU**
Example usage:

```sh
$ mint which Carthage/Carthage@0.29.0 carthage
/usr/local/lib/mint/packages/github.com_Carthage_Carthage/build/0.29.0/carthage
```

```sh
$ mint which LinusU/RasterizeXCAssets 
/usr/local/lib/mint/packages/github.com_LinusU_RasterizeXCAssets/build/1.0.0-alpha.2/RasterizeXCAssets
```

```sh
$ mint which carthage                         
/usr/local/lib/mint/packages/github.com_Carthage_Carthage/build/0.29.0/carthage
```

```sh
$ mint which LinusU/NotFound        
🌱  Git repo not found at "https://github.com/LinusU/NotFound.git"
```

### CODE REVIEW

**Comment by toshi0383** [comment]
`which` from UNIX doesn’t follow simlinks, does it?
Maybe it should be renamed to something else.

**Comment by yonaskolb** [comment]
@LinusU what's the motivation for a feature like this?

@toshi0383 good point, though this isn't following symlinks as it's the path used in `mint run` not the global install path

**Comment by LinusU** [comment]
> what's the motivation for a feature like this?

My main use case was being able to pass these paths into other programs that use the binary. e.g. passing the path to Carthage to XcodeGen.

**Comment by yonaskolb** [comment]
You should just be able to pass `mint run {tool}` and just call that instead of `{tool}`

**Comment by mrgrauel** [comment]
For fastlane usage it would be good to know the path.

**Comment by SpacyRicochet** [comment]
Seconding @mrgrauel's comment. 

We'd like to use Mint in combination with Fastlane, but without linking the binaries globally, since they might conflict with other versions in use by other projects. 

However, Fastlane isn't Mint-aware, so we can't for the `swiftLint` action to use `mint run swiftlint`. Instead, we could supply the path of the binary that would be used, but mint doesn't give us a way of retrieving that binary.

So, this PR would be a great addition in our opinion.

**Comment by sarastro-nl** [comment]
> For fastlane usage it would be good to know the path.

Absolutely true! Now I have this ugly hack in my Fastfile just to find out the path to swiftlint:
```
def lint
  swiftlint_directory = sh('sed -n -e "s/.*swiftlint@\(.*\)/\1/p" ../Mintfile | xargs find /usr/local/lib/mint -name | grep swiftlint | tr -d "\n"')
  swiftlint(
    executable: "#{swiftlint_directory}/swiftlint",
    config_file: "../SwiftLint/swiftlint.yml",
    strict: true,
    reporter: "junit",
    output_file: "output/swiftlint.junit"
  )
end
```

**Comment by yonaskolb** [comment]
I'll add this feature this weekend after https://github.com/yonaskolb/Mint/issues/145

**Comment by yonaskolb** [comment]
Reimplemented in https://github.com/yonaskolb/Mint/pull/162
Thanks for the work here @LinusU!

**Comment by hilsenrat** [comment]
For anyone stumbling upon this PR, I execute Swiftlint (From a Mintfile) via Fastlane like that:

`
    SWIFTLINT_PATH = sh("mint which swiftlint -m ../Mintfile | tr -d '\n'")
    swiftlint(
      executable: "#{SWIFTLINT_PATH}"
    )
`

**Comment by ArtFeel** [comment]
@hilsenrat Thanks for tip with ` | tr -d '\n'`!
 
I don't know why, but without that addition, `sh` action automatically execute binary for a path. For example this code:
```
lane :lint do
  sh("which brew")
end
```
Produce that output:
```
------------------------
--- Step: which brew ---
------------------------
$ which brew
▸ /usr/local/bin/brew
Example usage:
  brew search TEXT|/REGEX/
  brew info [FORMULA|CASK...]
  brew install FORMULA|CASK...
  brew update
  brew upgrade [FORMULA|CASK...]
  brew uninstall FORMULA|CASK...
  brew list [FORMULA|CASK...]
```

**Pull request closed without merging**
