### PR TITLE
Integrate SwiftCLI

### LINKED ISSUE #37: Support stdin
This would allow a swift executable to ask for user input

### PR DESCRIPTION
**Pull request by yonaskolb**
- [x] support stdin. fix #37
- [x] improve error output
- [x] print error to stderr
- [x] replace SwiftShell with SwiftCLI 
- [x] customizable stdout and stderr streams
- [x] show SPM build steps
- [x] replace SPM argument parsing with SwiftCLI

### CODE REVIEW

**Comment by yonaskolb** [comment]
@jakeheis I'm having some trouble with `SwiftCLI.LineStream`. I'm using it to filter the stdout of `swift build` to show summarized information, as can be seen here https://github.com/yonaskolb/Mint/pull/78/files#diff-29be028ae7ac6952c920e62a52a86416R283.
The problem is that the output only gets passed to the `LineStream` closure once the whole command has completed and in the wrong order. 
Could you have a look and see what the issue is? Is it something to do with stream flushing?

You can see the behaviour by running the following in the root directory
```sh
swift run mint update yonaskolb/xcodegen
🌱  Finding latest version of xcodegen
🌱  Resolved latest version of xcodegen to 1.9.0
🌱  Cloning https://github.com/yonaskolb/xcodegen.git 1.9.0...
🌱  Building xcodegen with SPM...
🌱  Compiling...
🌱  Installing...
🌱  Copying resources for xcodegen: SettingPresets ...
🌱  Installed xcodegen 1.9.0
🌱  Linking...
🌱  Fetching Dependencies...
🌱  Resolving Dependencies...
🌱  Linked xcodegen 1.9.0 to /usr/local/bin, replacing version 1.9.0.
```

As you see above the output is incorrect and at the wrong time. It should show fetching, resolving, compiling, linking under `Building xcodegen with SPM`

**Comment by jakeheis** [comment]
Confusingly, this actually seems to be the order which `swift` sends output through a pipe.

If I run that build command on Mint itself and have it output directly to the terminal, then the output is in the correct order:
```shell
> swift package reset
> swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.10 -Xswiftc -static-stdlib
Fetching https://github.com/apple/swift-package-manager.git
Fetching https://github.com/jakeheis/SwiftCLI
Fetching https://github.com/onevcat/Rainbow.git
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/kylef/Spectre.git
...
```

but if I run it and pipe it to `cat` than I get the order you're getting:

```shell
> swift package reset
> swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.10 -Xswiftc -static-stdlib | cat
Compile clibc libc.c
Compile Swift Module 'PathKit' (1 sources)
Compile Swift Module 'Rainbow' (11 sources)
Compile Swift Module 'SwiftCLI' (20 sources)
Compile Swift Module 'SPMLibc' (1 sources)
Compile Swift Module 'POSIX' (11 sources)
...
Linking ./.build/x86_64-apple-macosx10.10/release/mint
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/onevcat/Rainbow.git
Fetching https://github.com/apple/swift-package-manager.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/jakeheis/SwiftCLI
Cloning https://github.com/kylef/PathKit.git
Resolving https://github.com/kylef/PathKit.git at 0.9.1
Cloning https://github.com/onevcat/Rainbow.git
Resolving https://github.com/onevcat/Rainbow.git at 2.1.0
Cloning https://github.com/apple/swift-package-manager.git
Resolving https://github.com/apple/swift-package-manager.git at 0.2.0
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.8.0
Cloning https://github.com/jakeheis/SwiftCLI
Resolving https://github.com/jakeheis/SwiftCLI at 5.0.0
```

In other words, the `LineStream` is faithfully passing on lines as it receives them, but `swift` seems to change its output depending on if it is printing to a pipe or not which makes little sense to me.

**Comment by yonaskolb** [comment]
Very strange. Do you recommend any workaround? Is there a way to have this summarised build output?

**Comment by jakeheis** [comment]
I'd forgotten that I actually dealt with this exact issue with Ice -- I dealt with it by calling `swift package -v resolve` first and transforming that output and then transforming `swift build` afterwards https://github.com/jakeheis/Ice/blob/master/Sources/Core/SPM.swift#L33

**Comment by yonaskolb** [comment]
Ok thanks.
I've removed that summarised functionality from this PR for now.

**Pull request merged**
