### PR TITLE
Feature/add ssh suppport

### PR DESCRIPTION
**Pull request by Lutzifer**
this implements #59 and supports installing using ssh git urls like "git@github.com:yonaskolb/Mint.git"

### CODE REVIEW

**Comment by yonaskolb** [comment]
Great addition, thanks @Lutzifer! :)

**Comment by yonaskolb** [comment]
It's strange, tests are failing for me locally when trying to clone `git@github.com:yonaskolb/simplepackage.git`. They pass on CI however. Any idea @Lutzifer? I shouldn't need to add any ssh keys to get tests to pass

**Comment by Lutzifer** [comment]
I would suggest removing the sshRepo from testRunCommand then.

**Comment by yonaskolb** [comment]
Yeah, I have already 👍

**Pull request merged**
