### PR TITLE
Update SwiftCLI to v6.0.3

### PR DESCRIPTION
**Pull request by Armenm**
SwiftCLI v6.0.3 has a partial fix for this issue https://github.com/yonaskolb/Mint/issues/217.
PathKit fix still in progress https://github.com/kylef/PathKit/issues/77

### CODE REVIEW

**Comment by mthole** [comment]
Running int this now myself. Thanks for getting this fix going!

**Review by yonaskolb — APPROVED** [review]
Thanks @Armenm!

**Comment by Lutzifer** [comment]
@yonaskolb Any ETA for the next release?

**Comment by yonaskolb** [comment]
A release will require Pathkit to be fixed and released first too

**Comment by Armenm** [comment]
Seems the PathKit is also fixed. https://github.com/kylef/PathKit/pull/80

**Pull request merged**
